apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: monitoring
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: rohithreddykota/prometheus_client_server:latest
          name: web-server
          ports:
            - containerPort: 9191
