apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: web-service
  annotations:
    play.prometheus/scrape: "true"
    play.prometheus/path: "/metrics"
    play.prometheus/port: "9191"
spec:
  selector:
    app: web
  ports:
    - port: 9191


