apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discover
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingress
    verbs: ["get", "list", "watch"]

